FROM node:19-alpine3.17 as deps

WORKDIR /app
COPY package.json yarn.lock ./
RUN npm install


FROM node:19-alpine3.17 as builder
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN npm run build


FROM klerith/express-spa-server as runner
WORKDIR /app
COPY --from=builder /app/dist /app/public
COPY ./assets ./public/assets

CMD [ "npm","start" ]
